services:
  vpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY_FILE=/run/secrets/privatekey
    secrets:
      - privatekey
    restart: unless-stopped
    dns:
      - 103.86.96.100
      - 103.86.99.100
      - 1.1.1.1

secrets:
  privatekey:
    file: nordvpn_private_key.txt
